//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IotManagerAPI.EmailSender {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailSender.SendMessageSoap")]
    public interface SendMessageSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем from из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        IotManagerAPI.EmailSender.SendEmailResponse SendEmail(IotManagerAPI.EmailSender.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmailResponse> SendEmailAsync(IotManagerAPI.EmailSender.SendEmailRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем from из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail_v1", ReplyAction="*")]
        IotManagerAPI.EmailSender.SendEmail_v1Response SendEmail_v1(IotManagerAPI.EmailSender.SendEmail_v1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail_v1", ReplyAction="*")]
        System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmail_v1Response> SendEmail_v1Async(IotManagerAPI.EmailSender.SendEmail_v1Request request);
        
        // CODEGEN: Контракт генерации сообщений с именем from из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        IotManagerAPI.EmailSender.SendSmsResponse SendSms(IotManagerAPI.EmailSender.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendSmsResponse> SendSmsAsync(IotManagerAPI.EmailSender.SendSmsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем from из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail_v2", ReplyAction="*")]
        IotManagerAPI.EmailSender.SendEmail_v2Response SendEmail_v2(IotManagerAPI.EmailSender.SendEmail_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail_v2", ReplyAction="*")]
        System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmail_v2Response> SendEmail_v2Async(IotManagerAPI.EmailSender.SendEmail_v2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail", Namespace="http://tempuri.org/", Order=0)]
        public IotManagerAPI.EmailSender.SendEmailRequestBody Body;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(IotManagerAPI.EmailSender.SendEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MessageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AttachFile;
        
        public SendEmailRequestBody() {
        }
        
        public SendEmailRequestBody(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile) {
            this.from = from;
            this.DisplayName = DisplayName;
            this.to = to;
            this.subject = subject;
            this.MessageText = MessageText;
            this.cc = cc;
            this.bcc = bcc;
            this.AttachFile = AttachFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public IotManagerAPI.EmailSender.SendEmailResponseBody Body;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(IotManagerAPI.EmailSender.SendEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendEmailResult;
        
        public SendEmailResponseBody() {
        }
        
        public SendEmailResponseBody(string SendEmailResult) {
            this.SendEmailResult = SendEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmail_v1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail_v1", Namespace="http://tempuri.org/", Order=0)]
        public IotManagerAPI.EmailSender.SendEmail_v1RequestBody Body;
        
        public SendEmail_v1Request() {
        }
        
        public SendEmail_v1Request(IotManagerAPI.EmailSender.SendEmail_v1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmail_v1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MessageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AttachFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int prmMailPriority;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AppName;
        
        public SendEmail_v1RequestBody() {
        }
        
        public SendEmail_v1RequestBody(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            this.from = from;
            this.DisplayName = DisplayName;
            this.to = to;
            this.subject = subject;
            this.MessageText = MessageText;
            this.cc = cc;
            this.bcc = bcc;
            this.AttachFile = AttachFile;
            this.prmMailPriority = prmMailPriority;
            this.AppName = AppName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmail_v1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail_v1Response", Namespace="http://tempuri.org/", Order=0)]
        public IotManagerAPI.EmailSender.SendEmail_v1ResponseBody Body;
        
        public SendEmail_v1Response() {
        }
        
        public SendEmail_v1Response(IotManagerAPI.EmailSender.SendEmail_v1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmail_v1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendEmail_v1Result;
        
        public SendEmail_v1ResponseBody() {
        }
        
        public SendEmail_v1ResponseBody(string SendEmail_v1Result) {
            this.SendEmail_v1Result = SendEmail_v1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public IotManagerAPI.EmailSender.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(IotManagerAPI.EmailSender.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageText;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string from, string to, string subject, string MessageText) {
            this.from = from;
            this.to = to;
            this.subject = subject;
            this.MessageText = MessageText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public IotManagerAPI.EmailSender.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(IotManagerAPI.EmailSender.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmail_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail_v2", Namespace="http://tempuri.org/", Order=0)]
        public IotManagerAPI.EmailSender.SendEmail_v2RequestBody Body;
        
        public SendEmail_v2Request() {
        }
        
        public SendEmail_v2Request(IotManagerAPI.EmailSender.SendEmail_v2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmail_v2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MessageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AttachFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int prmMailPriority;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AppName;
        
        public SendEmail_v2RequestBody() {
        }
        
        public SendEmail_v2RequestBody(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            this.from = from;
            this.DisplayName = DisplayName;
            this.to = to;
            this.subject = subject;
            this.MessageText = MessageText;
            this.cc = cc;
            this.bcc = bcc;
            this.AttachFile = AttachFile;
            this.prmMailPriority = prmMailPriority;
            this.AppName = AppName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmail_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail_v2Response", Namespace="http://tempuri.org/", Order=0)]
        public IotManagerAPI.EmailSender.SendEmail_v2ResponseBody Body;
        
        public SendEmail_v2Response() {
        }
        
        public SendEmail_v2Response(IotManagerAPI.EmailSender.SendEmail_v2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmail_v2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendEmail_v2Result;
        
        public SendEmail_v2ResponseBody() {
        }
        
        public SendEmail_v2ResponseBody(string SendEmail_v2Result) {
            this.SendEmail_v2Result = SendEmail_v2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendMessageSoapChannel : IotManagerAPI.EmailSender.SendMessageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMessageSoapClient : System.ServiceModel.ClientBase<IotManagerAPI.EmailSender.SendMessageSoap>, IotManagerAPI.EmailSender.SendMessageSoap {
        
        public SendMessageSoapClient() {
        }
        
        public SendMessageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMessageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMessageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMessageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IotManagerAPI.EmailSender.SendEmailResponse IotManagerAPI.EmailSender.SendMessageSoap.SendEmail(IotManagerAPI.EmailSender.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public string SendEmail(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile) {
            IotManagerAPI.EmailSender.SendEmailRequest inValue = new IotManagerAPI.EmailSender.SendEmailRequest();
            inValue.Body = new IotManagerAPI.EmailSender.SendEmailRequestBody();
            inValue.Body.from = from;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.MessageText = MessageText;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.AttachFile = AttachFile;
            IotManagerAPI.EmailSender.SendEmailResponse retVal = ((IotManagerAPI.EmailSender.SendMessageSoap)(this)).SendEmail(inValue);
            return retVal.Body.SendEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmailResponse> IotManagerAPI.EmailSender.SendMessageSoap.SendEmailAsync(IotManagerAPI.EmailSender.SendEmailRequest request) {
            return base.Channel.SendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmailResponse> SendEmailAsync(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile) {
            IotManagerAPI.EmailSender.SendEmailRequest inValue = new IotManagerAPI.EmailSender.SendEmailRequest();
            inValue.Body = new IotManagerAPI.EmailSender.SendEmailRequestBody();
            inValue.Body.from = from;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.MessageText = MessageText;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.AttachFile = AttachFile;
            return ((IotManagerAPI.EmailSender.SendMessageSoap)(this)).SendEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IotManagerAPI.EmailSender.SendEmail_v1Response IotManagerAPI.EmailSender.SendMessageSoap.SendEmail_v1(IotManagerAPI.EmailSender.SendEmail_v1Request request) {
            return base.Channel.SendEmail_v1(request);
        }
        
        public string SendEmail_v1(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            IotManagerAPI.EmailSender.SendEmail_v1Request inValue = new IotManagerAPI.EmailSender.SendEmail_v1Request();
            inValue.Body = new IotManagerAPI.EmailSender.SendEmail_v1RequestBody();
            inValue.Body.from = from;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.MessageText = MessageText;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.AttachFile = AttachFile;
            inValue.Body.prmMailPriority = prmMailPriority;
            inValue.Body.AppName = AppName;
            IotManagerAPI.EmailSender.SendEmail_v1Response retVal = ((IotManagerAPI.EmailSender.SendMessageSoap)(this)).SendEmail_v1(inValue);
            return retVal.Body.SendEmail_v1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmail_v1Response> IotManagerAPI.EmailSender.SendMessageSoap.SendEmail_v1Async(IotManagerAPI.EmailSender.SendEmail_v1Request request) {
            return base.Channel.SendEmail_v1Async(request);
        }
        
        public System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmail_v1Response> SendEmail_v1Async(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            IotManagerAPI.EmailSender.SendEmail_v1Request inValue = new IotManagerAPI.EmailSender.SendEmail_v1Request();
            inValue.Body = new IotManagerAPI.EmailSender.SendEmail_v1RequestBody();
            inValue.Body.from = from;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.MessageText = MessageText;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.AttachFile = AttachFile;
            inValue.Body.prmMailPriority = prmMailPriority;
            inValue.Body.AppName = AppName;
            return ((IotManagerAPI.EmailSender.SendMessageSoap)(this)).SendEmail_v1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IotManagerAPI.EmailSender.SendSmsResponse IotManagerAPI.EmailSender.SendMessageSoap.SendSms(IotManagerAPI.EmailSender.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string from, string to, string subject, string MessageText) {
            IotManagerAPI.EmailSender.SendSmsRequest inValue = new IotManagerAPI.EmailSender.SendSmsRequest();
            inValue.Body = new IotManagerAPI.EmailSender.SendSmsRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.MessageText = MessageText;
            IotManagerAPI.EmailSender.SendSmsResponse retVal = ((IotManagerAPI.EmailSender.SendMessageSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendSmsResponse> IotManagerAPI.EmailSender.SendMessageSoap.SendSmsAsync(IotManagerAPI.EmailSender.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendSmsResponse> SendSmsAsync(string from, string to, string subject, string MessageText) {
            IotManagerAPI.EmailSender.SendSmsRequest inValue = new IotManagerAPI.EmailSender.SendSmsRequest();
            inValue.Body = new IotManagerAPI.EmailSender.SendSmsRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.MessageText = MessageText;
            return ((IotManagerAPI.EmailSender.SendMessageSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IotManagerAPI.EmailSender.SendEmail_v2Response IotManagerAPI.EmailSender.SendMessageSoap.SendEmail_v2(IotManagerAPI.EmailSender.SendEmail_v2Request request) {
            return base.Channel.SendEmail_v2(request);
        }
        
        public string SendEmail_v2(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            IotManagerAPI.EmailSender.SendEmail_v2Request inValue = new IotManagerAPI.EmailSender.SendEmail_v2Request();
            inValue.Body = new IotManagerAPI.EmailSender.SendEmail_v2RequestBody();
            inValue.Body.from = from;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.MessageText = MessageText;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.AttachFile = AttachFile;
            inValue.Body.prmMailPriority = prmMailPriority;
            inValue.Body.AppName = AppName;
            IotManagerAPI.EmailSender.SendEmail_v2Response retVal = ((IotManagerAPI.EmailSender.SendMessageSoap)(this)).SendEmail_v2(inValue);
            return retVal.Body.SendEmail_v2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmail_v2Response> IotManagerAPI.EmailSender.SendMessageSoap.SendEmail_v2Async(IotManagerAPI.EmailSender.SendEmail_v2Request request) {
            return base.Channel.SendEmail_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<IotManagerAPI.EmailSender.SendEmail_v2Response> SendEmail_v2Async(string from, string DisplayName, string to, string subject, string MessageText, string cc, string bcc, string AttachFile, int prmMailPriority, string AppName) {
            IotManagerAPI.EmailSender.SendEmail_v2Request inValue = new IotManagerAPI.EmailSender.SendEmail_v2Request();
            inValue.Body = new IotManagerAPI.EmailSender.SendEmail_v2RequestBody();
            inValue.Body.from = from;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.MessageText = MessageText;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.AttachFile = AttachFile;
            inValue.Body.prmMailPriority = prmMailPriority;
            inValue.Body.AppName = AppName;
            return ((IotManagerAPI.EmailSender.SendMessageSoap)(this)).SendEmail_v2Async(inValue);
        }
    }
}
